config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :students do
    resources :drop_in_histories
    resources :weekly_appointments, :scheduled_appointments, except: :create
  end

  resources :student_queues, except: :create

  root 'students#new'
  get 'students/:id/sign_in' => 'students#sign_in', as: :sign_in_student
  get 'student_queues/:id/wait_time' => 'student_queues#wait_time', as: :wait_time_student_queue
  get 'student_queues/:id/confirm' => 'student_queues#confirm', as: :confirm_student_queue
  get 'student_queues/:id/remove' => 'student_queues#remove', as: :remove_student_queue

  get 'student_queues/:id/create' => 'student_queues#create', as: :create_student_queue
  get 'weekly_appointments/:student_id/create' => 'weekly_appointments#create', as: :create_weekly_appointment
  get 'scheduled_appointments/:student_id/create' => 'scheduled_appointments#create', as: :create_scheduled_appointment

end

app/models/student_queue.rb
class StudentQueue < ActiveRecord::Base
  self.primary_key = :student_id
  belongs_to :student
end

app/controllers/student_queues_controller.rb
class StudentQueuesController < ApplicationController
  include TutorSecurityConcern
  def index
	  @queue_entries = StudentQueue.order('created_at')
    render "student_queues/index"
  end

  def wait_time
    @sorted_results = StudentQueue.order('created_at')
    @wait_pos = 0
    @sorted_results.each do |entry|
      break if "#{entry.student_id}" == params[:id]
      @wait_pos += 1
    end

	  @wait_time = @wait_pos * 30
	  
	  #will need the student's id in when confirming, so we pass it around
	  @student = Student.where(:sid => params[:id]) 
  end
    
  def new
    # render new template	
  end

  def create
    student = Student.find(params[:id]) #after nesting student_queue routes, {:id => :student_id}
    if student.student_queue.nil?
      student.build_student_queue(:course => params[:course])
      student.save
    else
      flash[:notice] = 'you are already in line'
    end
    redirect_to wait_time_student_queue_path(student.sid)
  end

  def confirm
    #wait in line
  end

  def destroy
    @student = Student.find(params[:id])
    @student.queue_to_history
    StudentQueue.destroy(@student.sid)
    # @student.student_queue.destroy
    #send student here if they decide to not to stay in line.
  end
end

app/helpers/student_queues_helper.rb
module StudentQueuesHelper
  def time_diff(start_time, end_time)
    seconds_diff = (start_time - end_time).to_i.abs

    hours = seconds_diff / 3600
    seconds_diff -= hours * 3600

    minutes = seconds_diff / 60
    # seconds_diff -= minutes * 60
    #
    # seconds = seconds_diff
    #
    # "#{hours.to_s.rjust(2, '0')}h:#{minutes.to_s.rjust(2, '0')}m:#{seconds.to_s.rjust(2, '0')}s"
    "#{hours.to_s.rjust(2, '0')}h:#{minutes.to_s.rjust(2, '0')}m"
  end
end

app/views/student_queues/confirm.html.erb
<h1> Hope to see you soon, you are in line!</h1>
<%= button_to 'Click here to sign in', new_student_request_path, :method => :get %>

app/views/student_queues/confirm.html.haml
%h1 you are in line
= link_to "Click here to sign in", new_student_path, :method => :get

app/views/student_queues/destroy.html.haml
%h1 you are not in line
= link_to "Click here to sign in and join the queue", new_student_path, :method => :get

app/views/student_queues/index.html.erb
<h1>Active Sessions</h1>
<table id="queue">
  <tr>
    <th>Start Time</th>
    <th>Student Name</th>
    <th>Tutor Name</th>
  </tr>
</table>
<tr></tr>
<h1>Drop-in</h1>
<table id="queue">
<tr>
  <th>Number</th>
  <th>Waiting</th>
  <th>Name</th>
  <th>Course</th>
</tr>

<tr>
<% @queue_entries.each do |entry| %>
      <tr id="q_row">
        <td></td>
        <td><%= time_diff(entry.created_at, Time.now) %></td>
        <td><%= %Q(#{entry.student.first_name} #{entry.student.last_name}) %></td>
        <td><%= entry.course %></td>
        <% end %>
      </tr>
</tr>
</table>

<h1>Weekly</h1>
<table id="queue">
<tr>
  <th>Number</th>
  <th>Waiting</th>
  <th>Name</th>
  <th>Course</th>
</tr>

<tr>
<% @queue_entries2.each do |entry| %>
      <tr id="q_row">
        <td></td>
        <td><%= time_diff(entry.created_at, Time.now) %></td>
        <td><%= %Q(#{entry.student.first_name} #{entry.student.last_name}) %></td>
        <td><%= entry.course %></td>
        <% end %>
      </tr>
</tr>
</table>

<h1>Scheduled</h1>
<table id="queue">
<tr>
  <th>Number</th>
  <th>Waiting</th>
  <th>Name</th>
  <th>Course</th>
</tr>

<tr>
<% @queue_entries3.each do |entry| %>
      <tr id="q_row">
        <td></td>
        <td><%= time_diff(entry.created_at, Time.now) %></td>
        <td><%= %Q(#{entry.student.first_name} #{entry.student.last_name}) %></td>
        <td><%= entry.course %></td>
        <% end %>
      </tr>
</tr>
</table>

app/views/student_queues/remove.html.erb
<h1>Hope to see you soon!</h1>
<%= button_to 'Click here to sign in', new_student_request_path, :method => :get %>

app/views/student_queues/wait_time.html.haml
%h1 Your estimated wait time is #{@wait_time} min
%ul#details
  %li
    Do you want to wait in line?
    = link_to 'YES', confirm_student_queue_path, :method => :get
    = link_to 'NO', student_queue_path, :method => :delete