config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :students do
    resources :drop_in_histories
    resources :weekly_appointments, :scheduled_appointments, except: :create
  end

  resources :student_queues, except: :create

  root 'students#new'
  get 'students/:id/sign_in' => 'students#sign_in', as: :sign_in_student
  get 'student_queues/:id/wait_time' => 'student_queues#wait_time', as: :wait_time_student_queue
  get 'student_queues/:id/confirm' => 'student_queues#confirm', as: :confirm_student_queue
  get 'student_queues/:id/remove' => 'student_queues#remove', as: :remove_student_queue

  get 'student_queues/:id/create' => 'student_queues#create', as: :create_student_queue
  get 'weekly_appointments/:student_id/create' => 'weekly_appointments#create', as: :create_weekly_appointment
  get 'scheduled_appointments/:student_id/create' => 'scheduled_appointments#create', as: :create_scheduled_appointment

end

app/helpers/student_requests_helper.rb
module StudentRequestsHelper
end

app/views/student_requests/home.html.erb
<h1>Writing Service Sign-in</h1>
<%= form_tag(wait_time_path, method: "post") do %>

     <!--<label class="sr-only" for="exampleInputEmail2">Email address</label> -->
    <%= label_tag(:last_name, "Last Name *") %>
    <%= text_field :last_name, :placeholder => "Last Name", id:"student_last_name", class: "form_signup"  %>

    <%= label_tag(:first_name, "First Name *") %>
    <%= text_field :first_name, :placeholder => "Last Name", id:"student_first_name", class: "form_signup"  %>

    <%= label_tag(:sid, "SID") %>
    <%= text_field :first_name, :placeholder => "000000000", id:"student_sid", class: "form_signup"  %>

    <%= label_tag(:email, "E-mail") %>
    <%= email_field :email, :placeholder => "example@gmail.com", id:"student_email", class: "form_signup"  %>
     
    <%= label_tag(:request_type, "Appointment") %>
    <%= radio_button_tag(:request_type, "Appointment") %>


    <%= label_tag(:course, "Course") %>
    <%= text_field :course, :placeholder => "History", id:"request_course", class: "form_signup"  %>

    <%= submit_tag("Submit") %>

<% end %>

app/views/student_requests/student_queue.html.erb
<h1>Queue</h1>


<table id="queue">
<tr>
  <th>Timestamp</th>
  <th>Name</th>
  <th>Course</th>
  <th>Tutor</th>
  <th>Start Time</th>
  
</tr>

<tr>
<% @queueentries.each do |entry| %>                    
  <td><%= entry.created_at %><td>
  <td><%= entry.student.first_name + " " + entry.student.last_name %><td>
  <td><%= entry.course %><td> 
  <td><%= entry.tutor.first_name %><td>
  <% if entry.start_time %>
	<td><%= "waiting" %><td>
  <% else %>
	<td><%= entry.start_time %><td>
  <% end %>
      
<% end %>
</tr>
</table>